name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.G_TOKEN }}
- name: Build the hello-docker Docker image
run: |
       docker build . --tag ghcr.io/${{ github.actor }}/docker_repo:latest
       docker run ghcr.io/${{ github.actor }}/docker_repo:latest
       docker push ghcr.io/${{ github.actor }}/docker_repo:latest